services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_IP=spark-master
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      - SPARK_MASTER_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_LOCAL_IP=spark-worker
      - PYSPARK_PYTHON=/usr/bin/python3
    volumes:
      - ./postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-app:
    image: bitnami/spark:latest
    container_name: spark-app
    hostname: spark-app
    volumes:
      - ./postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_CLASSPATH=/opt/spark/jars/postgresql-42.7.5.jar
    command: >
      spark-submit
      --master spark://spark-master:7077
      --driver-class-path /opt/spark/jars/postgresql-42.7.5.jar
      --jars /opt/spark/jars/postgresql-42.7.5.jar
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - spark-network

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    hostname: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test_view
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"  # Jupyter Notebook
    volumes:
      - ./postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar
      - ../examples_spark:/home/examples_spark
    environment:
      - JUPYTER_TOKEN=mi_token
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network

volumes:
  postgres_data:

networks:
  spark-network:
    driver: bridge